export * from './lib/services/categories.service'
export * from './lib/services/products.service'
export * from './lib/models/category.model'
export * from './lib/models/product.model'
export * from './lib/products.module'
export * from './lib/pipes/category-name.pipe'
export * from './lib/components/categories-banner/categories-banner.component'

export * from './lib/components/product-detail/product-detail.component'
export * from './lib/components/products-list/products-list.component'
export * from './lib/components/featured-products/featured-products.component'
export * from './lib/components/product-search/product-search.component'
